In [1]:
import sklearn
from sklearn import metrics
import numpy as np
#这种调用方法会导致在下一次重复使用xx_score时出现错误
y_true = [0, 1, 1, 0, 1, 0]
y_pred = [1, 1, 1, 0, 0, 1]
print(sklearn.metrics.accuracy_score(y_true,y_pred))
precision = sklearn.metrics.precision_score(y_true, y_pred, average='binary')
recall = sklearn.metrics.recall_score(y_true, y_pred, average='binary')
f1_score = sklearn.metrics.f1_score(y_true, y_pred, average='binary') # 2*Precision*Recall/(P+R)

print(precision, recall, f1_score)

0.5
0.5 0.6666666666666666 0.5714285714285715


#### 准确P = TP / (TP+FP)
#### 召回R = TP / (TP+FN)
#### F1 = 2 * P * R / (P+R) 
本质上是P和R的算术平均

In [2]:
from sklearn import metrics
#y_true = [1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4]
#y_pred = [1, 1, 1, 3, 3, 2, 2, 3, 3, 3, 4, 3, 4, 3]
y_true = [1,2,3,4,1]
y_pred = [1,2,3,0,2]
print(sklearn.metrics.accuracy_score(y_true,y_pred))
print(sklearn.metrics.precision_score(y_true,y_pred,average='micro'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='micro'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='micro'))
print(sklearn.metrics.f1_score(y_true,y_pred,labels=[1,2,3,4],average='micro'))
#labels指定计算的labels, 指定范围外的错误值算作缺失值,范围内的错值算错值 

0.6
0.6
0.6
0.6
0.6666666666666665


#### 'micro':通过先计算总体的TP，FN和FP的数量，再计算F1
若预测值没有缺失（都在labels范围内）FP等于FP，P=R=F1

#### 'macro':分别计算每个类别的P,R求得F1，然后做平均（各类别F1的权重相同）
#### 'weighted':对每一类别的f1_score进行加权平均，权重为各类别数在y_true中所占比例
加权的macro，这可能导致f1值不在P和R之间
#### None：返回每一类各自的f1_score，得到一个array
#### 'binary': 只对二分类问题有效，返回由pos_label指定的类的f1_score
#### 'sample': 对每一个实例进行计算，并找到平均值，和accuracy_score不同，只对多分类有用

In [51]:
import pandas as pd
y_true = pd.DataFrame([[1,0,0],[1,0,0]],columns=['l1','l2','l3'])
y_pred = pd.DataFrame([[1,0,0],[0,1,0]],columns=['l1','l2','l3'])
print(sklearn.metrics.precision_score(y_true,y_pred,average='macro'))
print(sklearn.metrics.precision_score(y_true,y_pred,average='micro'))
print(metrics.classification_report(y_true,y_pred))

0.3333333333333333
0.5
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0

   micro avg       0.50      0.50      0.50         2
   macro avg       0.33      0.17      0.22         2
weighted avg       1.00      0.50      0.67         2
 samples avg       0.50      0.50      0.50         2



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [52]:
y_true

l1  l2  l3
0   1   0   0
1   1   0   0

In [46]:
y_pred

l1  l2  l3
0   1   0   0
1   0   1   0

In [3]:
y_true = [1,2,3,4,1]
y_pred = [1,2,3,0,2]
print(sklearn.metrics.precision_score(y_true,y_pred,average='macro'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='macro'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='macro'))
print(sklearn.metrics.f1_score(y_true,y_pred,labels=[1,2,3,4],average='macro'))

0.625
0.75
0.6666666666666666
0.6666666666666666


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [4]:
y_true = [1,2,3,4,1]
y_pred = [1,2,3,0,2]
print(sklearn.metrics.precision_score(y_true,y_pred,average='weighted'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='weighted'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='weighted'))
print(sklearn.metrics.f1_score(y_true,y_pred,labels=[1,2,3,4],average='weighted'))

0.625
0.75
0.6666666666666666
0.6666666666666666


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
y_true = [1,2,3,4,1]
y_pred = [1,2,3,0,2]
print(sklearn.metrics.precision_score(y_true,y_pred,average=None))
print(sklearn.metrics.recall_score(y_true,y_pred,average=None))
print(sklearn.metrics.f1_score(y_true,y_pred,average=None))
print(sklearn.metrics.f1_score(y_true,y_pred,labels=[1,2,3,4],average=None))

[0.  1.  0.5 1.  0. ]
[0.  0.5 1.  1.  0. ]
[0.         0.66666667 0.66666667 1.         0.        ]
[0.66666667 0.66666667 1.         0.        ]


In [0]:
y_true = [1,2,3,4,1]
y_pred = [1,2,3,0,2]

print(sklearn.metrics.precision_score(y_true,y_pred,average='samples'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='samples'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='samples'))
print(sklearn.metrics.f1_score(y_true,y_pred,labels=[1,2,3,4],average='samples'))


In [0]:
from sklearn import metrics
 
y_test    = [1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4]
y_predict = [1, 1, 1, 3, 3, 2, 2, 3, 3, 3, 4, 3, 4, 3]
 
print('准确率:', metrics.accuracy_score(y_test, y_predict)) #预测准确率输出
 
print('宏平均精确率:',metrics.precision_score(y_test,y_predict,average='macro')) #预测宏平均精确率输出
print('微平均精确率:', metrics.precision_score(y_test, y_predict, average='micro')) #预测微平均精确率输出
print('加权平均精确率:', metrics.precision_score(y_test, y_predict, average='weighted')) #预测加权平均精确率输出
 
print('宏平均召回率:',metrics.recall_score(y_test,y_predict,average='macro'))#预测宏平均召回率输出
print('微平均召回率:',metrics.recall_score(y_test,y_predict,average='micro'))#预测微平均召回率输出
print('加权平均召回率:',metrics.recall_score(y_test,y_predict,average='weighted'))#预测加权平均召回率输出
 
print('宏平均F1-score:',metrics.f1_score(y_test,y_predict,labels=[1,2,3,4],average='macro'))#预测宏平均f1-score输出
print('微平均F1-score:',metrics.f1_score(y_test,y_predict,labels=[1,2,3,4],average='micro'))#预测微平均f1-score输出
print('加权平均F1-score:',metrics.f1_score(y_test,y_predict,labels=[1,2,3,4],average='weighted'))#预测加权平均f1-score输出
 
print('混淆矩阵输出:\n',metrics.confusion_matrix(y_test,y_predict,labels=[1,2,3,4]))#混淆矩阵输出
print('分类报告:\n', metrics.classification_report(y_test, y_predict,labels=[1,2,3,4]))#分类报告输出

准确率: 0.5714285714285714
宏平均精确率: 0.6964285714285714
微平均精确率: 0.5714285714285714
加权平均精确率: 0.7755102040816327
宏平均召回率: 0.5666666666666667
微平均召回率: 0.5714285714285714
加权平均召回率: 0.5714285714285714
宏平均F1-score: 0.5791666666666666
微平均F1-score: 0.5714285714285714
加权平均F1-score: 0.6154761904761905
混淆矩阵输出:
 [[3 0 2 0]
 [0 2 2 0]
 [0 0 2 1]
 [0 0 1 1]]
分类报告:
               precision    recall  f1-score   support

           1       1.00      0.60      0.75         5
           2       1.00      0.50      0.67         4
           3       0.29      0.67      0.40         3
           4       0.50      0.50      0.50         2

   micro avg       0.57      0.57      0.57        14
   macro avg       0.70      0.57      0.58        14
weighted avg       0.78      0.57      0.62        14



#### *  Hamming Loss
The Hamming loss is the fraction of labels that are incorrectly predicted.
#### *  zero_one_loss
the fraction of misclassifications #等于 1-accuracy

In [0]:
2/9

0.2222222222222222

In [0]:
y_true = np.array([[1, 1, 0], [0, 1, 0], [1, 1, 0]])
y_pred = np.array([[1, 1, 0], [0, 1, 1], [0, 1, 0]]) 
# print(sklearn.metrics.accuracy_score(y_true, y_pred)) #全部标签正确的比例数
# print(sklearn.metrics.accuracy_score(y_true, y_pred, normalize=False)) 
# print(sklearn.metrics.zero_one_loss(y_true, y_pred))  #1-全部正确的比例数
# print(sklearn.metrics.zero_one_loss(y_true, y_pred, normalize=False))
# print(sklearn.metrics.hamming_loss(y_true, y_pred))
print(sklearn.metrics.precision_score(y_true,y_pred, average='micro'))



0.8


In [0]:
# Precision为1的话，所有本来是0的，没有给预测成1
# Recall为1的话，所有为1的，都被预测到了

#micro
print(sklearn.metrics.precision_score(y_true,y_pred,average='macro'))  
print(sklearn.metrics.recall_score(y_true,y_pred,average='macro'))  
print(sklearn.metrics.f1_score(y_true,y_pred,average='macro'))

print('\n')
#macro
print(sklearn.metrics.precision_score(y_true,y_pred,average='micro'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='micro'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='micro'))

print('\n')
#weighted
print(sklearn.metrics.precision_score(y_true,y_pred,average='weighted'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='weighted'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='weighted'))

print('\n')
#samples
print(sklearn.metrics.precision_score(y_true,y_pred,average='samples'))
print(sklearn.metrics.recall_score(y_true,y_pred,average='samples'))
print(sklearn.metrics.f1_score(y_true,y_pred,average='samples'))

print(sklearn.metrics.classification_report(y_true, y_pred))

0.3333333333333333
0.6666666666666667
0.2222222222222222


0.6666666666666666
0.5
0.5555555555555555


0.8
0.8
0.8000000000000002


1.0
0.8
0.8666666666666666


0.8333333333333334
0.8333333333333334
0.7777777777777777
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         3
           2       0.00      0.00      0.00         0

   micro avg       0.80      0.80      0.80         5
   macro avg       0.67      0.50      0.56         5
weighted avg       1.00      0.80      0.87         5
 samples avg       0.83      0.83      0.78         5

